### ISSUE TITLE
TLS / HTTPS support

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB.github.io#17]
https://librepcb.org currently gives a certificate error. We should configure https correctly: See https://help.github.com/articles/securing-your-github-pages-site-with-https/.
I would fix it myself, but I don't have the necessary permissions on this repository to do it.

**Comment by rnestler** [comment]
>  There we have a HTTPS reverse proxy, so it's a no-brainer to set up HTTPS.

It's also a no-brainer with GitHub pages :wink: just enable it in the settings.

**Comment by ubruhin** [comment]
> It's also a no-brainer with GitHub pages wink just enable it in the settings.

OK you're now admin, just do it :wink:

**Comment by rnestler** [comment]
> OK you're now admin, just do it wink

I'd need to change the DNS record, I guess I'm not admin there :stuck_out_tongue_closed_eyes: 

> If you configured your custom domain using an A record, your A record must point to one of the following IP addresses for HTTPS to work:
>
>    185.199.108.153
    185.199.109.153
    185.199.110.153
    185.199.111.153

Better would be an ALIAS or ANAME record, see [here](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-an-alias-or-aname-record-with-your-dns-provider) for more info.

**Comment by dbrgn** [comment]
There is no such thing as an ANAME or ALIAS record in DNS: https://en.wikipedia.org/wiki/CNAME_record#ANAME_record

Also, I doubt that the shared hosting provider @ubruhin uses offers such dynamic DNS resolution mechanisms.

**Comment by ubruhin** [comment]
> I'd need to change the DNS record

I thought...

> just enable it in the settings.

? :wink: 

> Better would be an ALIAS or ANAME record, see here for more info.

IMHO every minute working on this is wasted time. With the new website it will work out-of-the-box.

**Comment by dbrgn** [comment]
The thing is, with administrative access as per https://github.com/LibrePCB/librepcb-rfcs/issues/27 neither of you would have wasted any time creating this issue or discussing about DNS :) It would have been a thing of 2 minutes, and https would simply have worked, vs now where broken HTTPS even hurts search engine ranking :wink: 

Anyways, so will there be a new website? You only mentioned that there might be a new one, but your post above is the first confirmation of that. Cool! :tada:

**Comment by rnestler** [comment]
> I can't give administrative access for the DNS entries anyway because my provider doesn't support that. And I don't want to share my credentials because I also have other domains on the same provider...

Could we transfer the ownership to a new owner which would be LibrePCB with an account where multiple people have access?

**Comment by ubruhin** [comment]
Website is now hosted on our own server, so TLS is enabled: https://librepcb.org
