### ISSUE TITLE
www.librepcb.org link broken

### ISSUE THREAD

**Issue by Symbian9** [LibrePCB/LibrePCB.github.io#21]
As LibrePCB organization on GitHub has link to `http://www.librepcb.org` on it's header, I just test click on this link:

- http://www.librepcb.org

As result got 404 page with next message:

> `404 Site www.librepcb.org is not served on this interface`

In same time `http://ibrepcb.org` working well.

**Comment by rnestler** [comment]
> As result got 404 page with next message:
>    404 Site www.librepcb.org is not served on this interface

Probably a missing redirect from www.librepcb.org to librepcb.org

**Comment by Symbian9** [comment]
Here is difference in GitHub organization link & this repo link

![pic.1](http://i.imgur.com/vmVDlfF.png)

![pic.2](http://i.imgur.com/UVQOwQV.png)

**Comment by ubruhin** [comment]
Fixed both: Changed link in organization, and added redirection for www.librepcb.org.

Thanks for reporting :)
